### PR TITLE
The next web clone

### PR DESCRIPTION
**Pull request by evansinho**
# Next Web Clone
### project consist of the following:
- A Navigation bar
- A hero section and a couple of more sections which are all responsive.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 


Hi @evansinho and @SafaErden, you have done a really great job with this project 👍 Project is responsive and it looks like the original ✋ great work 💯 However, there are a few changes we could implement to improve our project. Find comments below:
- The TNW logo appears on the medium screen, but it disappears on the original. Kindly check the images below for more details
```Currently```
ldd1
```Original```
ldd
- Let us compare both images and make the changes on the medium screen
```Currently```
ld
```Original```
ld1
- Let us apply the DRY rule so we do not repeat code like ```list-style:none```, ```text-decoration:none``` etc. Let us look into our CSS file and let us apply the DRY rule

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by sumancrest0001** [comment]
**STATUS: CHANGES REQUIRED**

**Awesome job TEAM :clap: :clap:** 
You have done a great job and fixed all the issues addressed by the previous TSE. You are very close to getting:+1: :+1:  for this project. Let's try to fix the following issues to ensure that it's a clone of the original site.

[REQUIRED] on the medium screen there is no other element in the navbar other than the search icon. Please check and fix the issue.
currently :point_down: 
Screenshot from 2020-04-11 19-43-40

It should be like this :point_down: 
Screenshot from 2020-04-11 19-51-38

**Comment by sumancrest0001** [comment]
[Required] Let's add some vertical margin between sections.

in your project :point_down: 
Screenshot from 2020-04-11 19-41-46

Should be :point_down: 
Screenshot from 2020-04-11 19-44-12

**Comment by sumancrest0001** [comment]
[REQUIRED] It looks very congested on the small screen. Let's add some margin and increase size of the article which helps us to achieve the original layout.

in the project :point_down: 
Screenshot from 2020-04-11 19-40-18

in the original site :point_down: :point_down: 
Screenshot from 2020-04-11 19-59-07

**Comment by sumancrest0001** [comment]
After making these changes we are good to move to the next project. Kindly make the suggested changes and submit the project next time.
Need support? Contact me on slack **Suman Shrestha.**

**Happy coding**

**Review by men32z — APPROVED** [review]
## Good job making the changes, you can merge.
before to merge consider make the following changes
- [ ] in the first review the TSE pointed that the logo that is in the big article should disappear in the middle screens, and you can see the screenshot in the first comment, try to hide the logo in middle screens.
- [ ] in the original page the nav(header) is sticky(fixed position). yours is also sticky but the black part shouldn't be sticky. try to make this change.

BlgS1sdIUAEybkW

### Status Approved

--Luis Preza

**Pull request merged**
